"""change roles from JSON to ARRAY

Revision ID: d1f1a645915a
Revises: 8a0a8e429f77
Create Date: 2026-02-21 21:11:12.427574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1f1a645915a'
down_revision = '8a0a8e429f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('oauth') # Commenting out to avoid issues if table doesn't exist
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('roles')
        batch_op.add_column(sa.Column('roles', sa.ARRAY(sa.String()), nullable=True, default=[]))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('roles')
        batch_op.add_column(sa.Column('roles', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # op.create_table('oauth', ... ) # implementation omitted for brevity
    # ### end Alembic commands ###
