"""Replace event_date with start_date and end_date in Event model

Revision ID: ffcc8f3a44c1
Revises: 9e989bb6b487
Create Date: 2026-02-21 15:47:08.029662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffcc8f3a44c1'
down_revision = '9e989bb6b487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_requests')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('event_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    op.create_table('club_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('club_requests_club_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('club_requests_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('club_requests_pkey'))
    )
    # ### end Alembic commands ###
